server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://106.15.238.69:8848/  #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
